 [language-server.gpt]
 command = "/Users/sushmitmacair/Projects/hackathons/valearnis/helix-gpt/dist/helix-gpt"

 [language-server.ts]
 command = "typescript-language-server"
 args = ["--stdio"]
 language-id = "javascript"

 [[language]]
 name = "typescript"
 language-servers = [
     "ts",
     "gpt"
 ]
